---
aegis-gateway:
  - name: test-secret-1
    env: devnet02
    type: gcp-secret-manager
    config:
      source: projects/732439461432/secrets/psql-dapps-ptr5gu-reader
      project: prj-dev-devnet02
      auth-profile: gcp-devnet02-target

  - name: aws-test-secret-2
    env: devnet02
    type: aws-secret-manager
    config:
      source: "arn:aws:secretsmanager:eu-west-1:081403079551:secret:psql-dapps-ptr4ae-user-JRIoC8"
      region: eu-west-1
      auth-profile: aws-eu-deploy-target

  - name: test-secret-1
    env: sitnet01
    type: gcp-secret-manager
    config:
      source: projects/732439461432/secrets/psql-dapps-ptr5gu-user
      project: prj-dev-devnet02

  
