aegis-link:
  - name: test-secret-1
    env: devnet02
    type: gcp-secret-manager
    outputs:
      - type: value
        destination: GCP_SECRET_DEV
      - type: file
        destination: ./tmp/secrets/dummy_secret_2.txt

  - name: test-secret-1
    env: sitnet01
    type: gcp-secret-manager
    outputs:
      - type: value
        destination: GCP_SECRET_SITNET

  - name: aws-test-secret-2
    env: devnet02
    type: aws-secret-manager
    outputs:
      - type: value
        destination: AWS_SECRET_DEV